# Generated by Django 4.2.4 on 2023-12-19 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('tik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tik',
            name='assign_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tik', to='users.client'),
        ),
        migrations.AddField(
            model_name='tik',
            name='files',
            field=models.FileField(default='default_file.txt', upload_to='files'),
        ),
    ]
