# Generated by Django 4.2.4 on 2023-12-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tik', '0002_tik_assign_to_tik_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tik',
            name='files',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='files/'),
        ),
    ]
