# Generated by Django 4.2.4 on 2023-12-21 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('tik', '0003_alter_tik_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tik',
            name='assign_to',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='tik', to='users.client'),
        ),
    ]
