# Generated by Django 4.2.4 on 2023-12-19 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='assign_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='users.client'),
        ),
    ]
