# Generated by Django 4.2.4 on 2023-12-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0002_alter_mission_assign_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='name',
        ),
        migrations.AddField(
            model_name='mission',
            name='priority',
            field=models.CharField(choices=[('1', 'first'), ('2', 'middle'), ('3', 'last')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='mission',
            name='task',
            field=models.TextField(default='new task', max_length=100),
        ),
    ]
