# Generated by Django 4.2.4 on 2023-12-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_super_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='money',
            field=models.IntegerField(default=10000),
        ),
    ]
