# Generated by Django 4.2.4 on 2023-12-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_client_active_alter_client_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_super',
        ),
        migrations.AddField(
            model_name='admin',
            name='is_super',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_super',
            field=models.BooleanField(default=False),
        ),
    ]
