# Generated by Django 4.2.4 on 2023-12-18 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_is_super_admin_is_super_client_is_super'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='moneyneed',
            field=models.IntegerField(default=0, verbose_name=0),
            preserve_default=False,
        ),
    ]
