# Generated by Django 4.2.4 on 2023-12-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_client_moneyneed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='moneyneed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
